PE-D Bug Fixes
AY2223S1-CS2103T-T11-1/tp pull request #156
Opened 2022-11-02 09:36 UTC by jasonchristopher21

Fix bugs found in PE-D

2022-11-04 09:39 UTC, mohamedsaf1 reviewed
LGTM. Adding equals methods to ensure no repetition in output for same commands.

2022-11-07 08:12 UTC, Eclipse-Dominator requested changes
Take note of some errors in the Name.java equals() implementation!

2022-11-07 08:12 UTC, Eclipse-Dominator commented on src/main/java/seedu/address/model/attribute/AttributeList.java
> -
Good idea to consolidate all the parse related methods

2022-11-07 08:12 UTC, Eclipse-Dominator commented on src/main/java/seedu/address/model/attribute/Email.java
> +            String otherEmail = email.value.replaceAll("\\s+", "");
email shouldn't have spaces if declared properly, so I think this part is not necessary!

2022-11-07 08:12 UTC, Eclipse-Dominator commented on src/main/java/seedu/address/model/attribute/Name.java
> +            String otherName = n.fullName.replaceAll("\\s+", "");
Perhaps it's better to do this conversion in the constructor?
i.e. change `super(TYPE, name)` to `super(TYPE, name.replaceAll("\\s+", " "))`;
This way we dont have to do this additional check?

2022-11-07 08:12 UTC, Eclipse-Dominator commented on src/main/java/seedu/address/model/attribute/Name.java
> +            String otherName = n.fullName.replaceAll("\\s+", "");
There is also a problem with this is that 
"Joh Natalie" will match "John Atalie"

2022-11-07 15:37 UTC, Eclipse-Dominator approved these changes

2022-11-07 15:37 UTC, merged